### ISSUE TITLE
Implement proper types for SaveReader which match Palworld repr

### ISSUE THREAD

**Issue by wojiaolw322** [tylercamp/palcalc#16]
https://github.com/CrystalFerrai/UeSaveGame/
https://github.com/xkp95175333/palworld-sdk/blob/main/SDK/Pal_structs.hpp

**Comment by tylercamp** [comment]
I'm going to close this as won't-fix since it's not a necessary change and I don't have any plans to go with this approach right now. 

A brief try of UeSaveGame shows that it takes longer to read a full save file and it's not able to read a Palworld save without errors. (i.e. I tried it and got an exception while it was attempting to read a string.) Note that this lib deserializes the entire save at once, and Palworld saves are compressed. My semi-lategame save decompresses to ~150MB.

Won't be using palworld-sdk right now since it hasn't been updated since it was first created, and while that repo was auto-generated with an exporter (where I could run that export myself), I'd rather stick with a well-maintained reference like palworld-save-tools (as mentioned in note (2) of my previous comment)
