### ISSUE TITLE
Error while startup

### ISSUE THREAD

**Issue by imtheluk** [tylercamp/palcalc#56]
Hi, I have a bit of a problem with palcalc, but i don't really think this is the problem there. 
In fact, when i launch palcalc, i get the famous "an error occured". But the thing is that I can't use any other save-related palworld tool, like xNul palworld-host-save-fix or palworld-save-tools.

I get this error, whatever i try to launch : 
File "C:\Users\imthe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 493, in property
    raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: ByteProperty (.SaveParameter.Level)

Do you have an idea about how to resolve this?

**Comment by tylercamp** [comment]
@imtheluk The latest version of Palworld, v0.3.7, includes some changes to the save file format which were incompatible with [palworld-save-tools](https://github.com/cheahjs/palworld-save-tools/) which I (and others) based my code on - the issue is being tracked in palworld-save-tools [here](https://github.com/cheahjs/palworld-save-tools/issues/187)

I just released Pal Calc [v1.7.5](https://github.com/tylercamp/palcalc/releases/tag/v1.7.5) based on the findings in the linked thread

**Comment by imtheluk** [comment]
Alright! 
The thing is, someone found a temporary solution, but i can't manage to do it correctly xd 
https://github.com/cheahjs/palworld-save-tools/issues/187#issuecomment-2359196290

**Comment by tylercamp** [comment]
@imtheluk Whoever wrote the software you're using will need to provide an update

**Comment by deafdudecomputers** [comment]
It appears after using my attachment of "temporary fix", @imtheluk was able to make it work again.

**Comment by imtheluk** [comment]
Yup, this fix works with all instances of palworld-save-tools, even if installed with python or pip.
You just have to know where to search
