### ISSUE TITLE
Low Memory Warnings

### ISSUE THREAD

**Issue by XXDarrienX** [tylercamp/palcalc#77]
So just started using this tool and constantly getting the low system memory errors for the solver steps.  I have more than 48gb of memory. Are there some settings I should change in my checking to reduce memory load?

**Comment by tylercamp** [comment]
Interesting, how much free memory is available? Are you running the app in a VM?

**Comment by tylercamp** [comment]
The memory monitor + warning was added since the addition of IV solving could lead to many GB of memory being used

The upcoming 1.10.3 update, which I plan to release later today, greatly improves memory efficiency so it should be safe for me to remove that check. I'm curious to know why this issue is happening for you though

**Comment by XXDarrienX** [comment]
Seems I do not have quite a bit left, I will need to close some things down while running this did not realize it was memory intensive.

**Comment by tylercamp** [comment]
The wiki's page on Breeding Settings talks about this indirectly, it refers to processing time rather than memory usage but they're directly related: https://github.com/tylercamp/palcalc/wiki/Breeding-Settings

Memory usage currently increases exponentially with the _number of_ passives, _number of_ IVs, and the value of the "Max Bred Irrelevant Passives" setting

For now, setting "Max Bred Irrelevant Passives" to 0 or 1 should be good enough to get useful results without taking up tons of memory

**Comment by XXDarrienX** [comment]
My mistake did not fully read the wiki
